name = "nav"
main = "src/index.js"
compatibility_date = "2025-12-17"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "nav-db"
database_id = "you_db_id"

# Environment variables
[vars]
JWT_SECRET = "ndlallzsdhfjhjfeksaguiknxv5168dfg5cao"

# Static assets
[assets]
directory = "./public"
